name: Checkout, install dependencies, and build dev and prod

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'release/**'

  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13]

    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "constellation/lib_asset.json"
          FILE_DATA: "{}"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "constellation/bootstrap-shell.js"
          FILE_DATA: "// placeholder for bootstrap-shell.js"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "constellation/constellation-core.placeholder.js"
          FILE_DATA: "// placeholder for constellaiton-core.js"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm run build:dev:ci
      - name: Run build:dev
        run: npm run build:dev
      - name: Run build:prod
        run: npm run build:prod
